//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpirithubCofe.Web.AramexRate
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class ClientInfo : object
    {
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string VersionField;
        
        private string AccountNumberField;
        
        private string AccountPinField;
        
        private string AccountEntityField;
        
        private string AccountCountryCodeField;
        
        private int SourceField;
        
        private string PreferredLanguageCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string AccountPin
        {
            get
            {
                return this.AccountPinField;
            }
            set
            {
                this.AccountPinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string AccountEntity
        {
            get
            {
                return this.AccountEntityField;
            }
            set
            {
                this.AccountEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string AccountCountryCode
        {
            get
            {
                return this.AccountCountryCodeField;
            }
            set
            {
                this.AccountCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PreferredLanguageCode
        {
            get
            {
                return this.PreferredLanguageCodeField;
            }
            set
            {
                this.PreferredLanguageCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class Transaction : object
    {
        
        private string Reference1Field;
        
        private string Reference2Field;
        
        private string Reference3Field;
        
        private string Reference4Field;
        
        private string Reference5Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference1
        {
            get
            {
                return this.Reference1Field;
            }
            set
            {
                this.Reference1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference2
        {
            get
            {
                return this.Reference2Field;
            }
            set
            {
                this.Reference2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference3
        {
            get
            {
                return this.Reference3Field;
            }
            set
            {
                this.Reference3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference4
        {
            get
            {
                return this.Reference4Field;
            }
            set
            {
                this.Reference4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference5
        {
            get
            {
                return this.Reference5Field;
            }
            set
            {
                this.Reference5Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class Address : object
    {
        
        private string Line1Field;
        
        private string Line2Field;
        
        private string Line3Field;
        
        private string CityField;
        
        private string StateOrProvinceCodeField;
        
        private string PostCodeField;
        
        private string CountryCodeField;
        
        private decimal LongitudeField;
        
        private decimal LatitudeField;
        
        private string BuildingNumberField;
        
        private string BuildingNameField;
        
        private string FloorField;
        
        private string ApartmentField;
        
        private string POBoxField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line1
        {
            get
            {
                return this.Line1Field;
            }
            set
            {
                this.Line1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line2
        {
            get
            {
                return this.Line2Field;
            }
            set
            {
                this.Line2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line3
        {
            get
            {
                return this.Line3Field;
            }
            set
            {
                this.Line3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StateOrProvinceCode
        {
            get
            {
                return this.StateOrProvinceCodeField;
            }
            set
            {
                this.StateOrProvinceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string PostCode
        {
            get
            {
                return this.PostCodeField;
            }
            set
            {
                this.PostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string BuildingNumber
        {
            get
            {
                return this.BuildingNumberField;
            }
            set
            {
                this.BuildingNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string BuildingName
        {
            get
            {
                return this.BuildingNameField;
            }
            set
            {
                this.BuildingNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Apartment
        {
            get
            {
                return this.ApartmentField;
            }
            set
            {
                this.ApartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string POBox
        {
            get
            {
                return this.POBoxField;
            }
            set
            {
                this.POBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentDetails", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class ShipmentDetails : object
    {
        
        private SpirithubCofe.Web.AramexRate.Dimensions DimensionsField;
        
        private SpirithubCofe.Web.AramexRate.Weight ActualWeightField;
        
        private SpirithubCofe.Web.AramexRate.Weight ChargeableWeightField;
        
        private string DescriptionOfGoodsField;
        
        private string GoodsOriginCountryField;
        
        private int NumberOfPiecesField;
        
        private string ProductGroupField;
        
        private string ProductTypeField;
        
        private string PaymentTypeField;
        
        private string PaymentOptionsField;
        
        private SpirithubCofe.Web.AramexRate.Money CustomsValueAmountField;
        
        private SpirithubCofe.Web.AramexRate.Money CashOnDeliveryAmountField;
        
        private SpirithubCofe.Web.AramexRate.Money InsuranceAmountField;
        
        private SpirithubCofe.Web.AramexRate.Money CashAdditionalAmountField;
        
        private string CashAdditionalAmountDescriptionField;
        
        private SpirithubCofe.Web.AramexRate.Money CollectAmountField;
        
        private string ServicesField;
        
        private SpirithubCofe.Web.AramexRate.ShipmentItem[] ItemsField;
        
        private SpirithubCofe.Web.AramexRate.DeliveryInstructions DeliveryInstructionsField;
        
        private SpirithubCofe.Web.AramexRate.AdditionalProperty[] AdditionalPropertiesField;
        
        private bool ContainsDangerousGoodsField;
        
        private SpirithubCofe.Web.AramexRate.Dimensions[] PieceDimensionsField;
        
        private bool IsTrueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SpirithubCofe.Web.AramexRate.Dimensions Dimensions
        {
            get
            {
                return this.DimensionsField;
            }
            set
            {
                this.DimensionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public SpirithubCofe.Web.AramexRate.Weight ActualWeight
        {
            get
            {
                return this.ActualWeightField;
            }
            set
            {
                this.ActualWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public SpirithubCofe.Web.AramexRate.Weight ChargeableWeight
        {
            get
            {
                return this.ChargeableWeightField;
            }
            set
            {
                this.ChargeableWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string DescriptionOfGoods
        {
            get
            {
                return this.DescriptionOfGoodsField;
            }
            set
            {
                this.DescriptionOfGoodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string GoodsOriginCountry
        {
            get
            {
                return this.GoodsOriginCountryField;
            }
            set
            {
                this.GoodsOriginCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NumberOfPieces
        {
            get
            {
                return this.NumberOfPiecesField;
            }
            set
            {
                this.NumberOfPiecesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string ProductGroup
        {
            get
            {
                return this.ProductGroupField;
            }
            set
            {
                this.ProductGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ProductType
        {
            get
            {
                return this.ProductTypeField;
            }
            set
            {
                this.ProductTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string PaymentType
        {
            get
            {
                return this.PaymentTypeField;
            }
            set
            {
                this.PaymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string PaymentOptions
        {
            get
            {
                return this.PaymentOptionsField;
            }
            set
            {
                this.PaymentOptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public SpirithubCofe.Web.AramexRate.Money CustomsValueAmount
        {
            get
            {
                return this.CustomsValueAmountField;
            }
            set
            {
                this.CustomsValueAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public SpirithubCofe.Web.AramexRate.Money CashOnDeliveryAmount
        {
            get
            {
                return this.CashOnDeliveryAmountField;
            }
            set
            {
                this.CashOnDeliveryAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public SpirithubCofe.Web.AramexRate.Money InsuranceAmount
        {
            get
            {
                return this.InsuranceAmountField;
            }
            set
            {
                this.InsuranceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public SpirithubCofe.Web.AramexRate.Money CashAdditionalAmount
        {
            get
            {
                return this.CashAdditionalAmountField;
            }
            set
            {
                this.CashAdditionalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string CashAdditionalAmountDescription
        {
            get
            {
                return this.CashAdditionalAmountDescriptionField;
            }
            set
            {
                this.CashAdditionalAmountDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public SpirithubCofe.Web.AramexRate.Money CollectAmount
        {
            get
            {
                return this.CollectAmountField;
            }
            set
            {
                this.CollectAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Services
        {
            get
            {
                return this.ServicesField;
            }
            set
            {
                this.ServicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public SpirithubCofe.Web.AramexRate.ShipmentItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public SpirithubCofe.Web.AramexRate.DeliveryInstructions DeliveryInstructions
        {
            get
            {
                return this.DeliveryInstructionsField;
            }
            set
            {
                this.DeliveryInstructionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public SpirithubCofe.Web.AramexRate.AdditionalProperty[] AdditionalProperties
        {
            get
            {
                return this.AdditionalPropertiesField;
            }
            set
            {
                this.AdditionalPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public bool ContainsDangerousGoods
        {
            get
            {
                return this.ContainsDangerousGoodsField;
            }
            set
            {
                this.ContainsDangerousGoodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public SpirithubCofe.Web.AramexRate.Dimensions[] PieceDimensions
        {
            get
            {
                return this.PieceDimensionsField;
            }
            set
            {
                this.PieceDimensionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public bool IsTrue
        {
            get
            {
                return this.IsTrueField;
            }
            set
            {
                this.IsTrueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dimensions", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class Dimensions : object
    {
        
        private double LengthField;
        
        private double WidthField;
        
        private double HeightField;
        
        private SpirithubCofe.Web.AramexRate.Weight ActualWeightField;
        
        private SpirithubCofe.Web.AramexRate.Weight ChargeableWeightField;
        
        private int NumberOfPiecesField;
        
        private string UnitField;
        
        private SpirithubCofe.Web.AramexRate.Weight VolumetricWeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public SpirithubCofe.Web.AramexRate.Weight ActualWeight
        {
            get
            {
                return this.ActualWeightField;
            }
            set
            {
                this.ActualWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public SpirithubCofe.Web.AramexRate.Weight ChargeableWeight
        {
            get
            {
                return this.ChargeableWeightField;
            }
            set
            {
                this.ChargeableWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int NumberOfPieces
        {
            get
            {
                return this.NumberOfPiecesField;
            }
            set
            {
                this.NumberOfPiecesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public SpirithubCofe.Web.AramexRate.Weight VolumetricWeight
        {
            get
            {
                return this.VolumetricWeightField;
            }
            set
            {
                this.VolumetricWeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weight", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class Weight : object
    {
        
        private string UnitField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Money", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class Money : object
    {
        
        private string CurrencyCodeField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryInstructions", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class DeliveryInstructions : object
    {
        
        private string OptionField;
        
        private string ReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Option
        {
            get
            {
                return this.OptionField;
            }
            set
            {
                this.OptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentItem", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class ShipmentItem : object
    {
        
        private string PackageTypeField;
        
        private int QuantityField;
        
        private SpirithubCofe.Web.AramexRate.Weight WeightField;
        
        private string CommentsField;
        
        private string ReferenceField;
        
        private SpirithubCofe.Web.AramexRate.Dimensions[] PiecesDimensionsField;
        
        private string CommodityCodeField;
        
        private string GoodsDescriptionField;
        
        private string CountryOfOriginField;
        
        private SpirithubCofe.Web.AramexRate.Money CustomsValueField;
        
        private string ContainerNumberField;
        
        private string Reference1Field;
        
        private string Reference2Field;
        
        private string Reference3Field;
        
        private string Reference4Field;
        
        private string Reference5Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PackageType
        {
            get
            {
                return this.PackageTypeField;
            }
            set
            {
                this.PackageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SpirithubCofe.Web.AramexRate.Weight Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public SpirithubCofe.Web.AramexRate.Dimensions[] PiecesDimensions
        {
            get
            {
                return this.PiecesDimensionsField;
            }
            set
            {
                this.PiecesDimensionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CommodityCode
        {
            get
            {
                return this.CommodityCodeField;
            }
            set
            {
                this.CommodityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string GoodsDescription
        {
            get
            {
                return this.GoodsDescriptionField;
            }
            set
            {
                this.GoodsDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CountryOfOrigin
        {
            get
            {
                return this.CountryOfOriginField;
            }
            set
            {
                this.CountryOfOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public SpirithubCofe.Web.AramexRate.Money CustomsValue
        {
            get
            {
                return this.CustomsValueField;
            }
            set
            {
                this.CustomsValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ContainerNumber
        {
            get
            {
                return this.ContainerNumberField;
            }
            set
            {
                this.ContainerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Reference1
        {
            get
            {
                return this.Reference1Field;
            }
            set
            {
                this.Reference1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Reference2
        {
            get
            {
                return this.Reference2Field;
            }
            set
            {
                this.Reference2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Reference3
        {
            get
            {
                return this.Reference3Field;
            }
            set
            {
                this.Reference3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Reference4
        {
            get
            {
                return this.Reference4Field;
            }
            set
            {
                this.Reference4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Reference5
        {
            get
            {
                return this.Reference5Field;
            }
            set
            {
                this.Reference5Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalProperty", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class AdditionalProperty : object
    {
        
        private string CategoryNameField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class Notification : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateDetails", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class RateDetails : object
    {
        
        private double AmountField;
        
        private double OtherAmount1Field;
        
        private double OtherAmount2Field;
        
        private double OtherAmount3Field;
        
        private double OtherAmount4Field;
        
        private double OtherAmount5Field;
        
        private double TotalAmountBeforeTaxField;
        
        private double TaxAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount1
        {
            get
            {
                return this.OtherAmount1Field;
            }
            set
            {
                this.OtherAmount1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount2
        {
            get
            {
                return this.OtherAmount2Field;
            }
            set
            {
                this.OtherAmount2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount3
        {
            get
            {
                return this.OtherAmount3Field;
            }
            set
            {
                this.OtherAmount3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount4
        {
            get
            {
                return this.OtherAmount4Field;
            }
            set
            {
                this.OtherAmount4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double OtherAmount5
        {
            get
            {
                return this.OtherAmount5Field;
            }
            set
            {
                this.OtherAmount5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double TotalAmountBeforeTax
        {
            get
            {
                return this.TotalAmountBeforeTaxField;
            }
            set
            {
                this.TotalAmountBeforeTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiRateDetails", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class MultiRateDetails : object
    {
        
        private string ProductGroupField;
        
        private string[] ProductTypesField;
        
        private string PaymentTypeField;
        
        private string ServicesField;
        
        private SpirithubCofe.Web.AramexRate.Weight ActualWeightField;
        
        private SpirithubCofe.Web.AramexRate.Money CashOnDeliveryAmountField;
        
        private SpirithubCofe.Web.AramexRate.Money InsuranceAmountField;
        
        private SpirithubCofe.Web.AramexRate.Money CustomsValueAmountField;
        
        private SpirithubCofe.Web.AramexRate.Money CollectAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductGroup
        {
            get
            {
                return this.ProductGroupField;
            }
            set
            {
                this.ProductGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] ProductTypes
        {
            get
            {
                return this.ProductTypesField;
            }
            set
            {
                this.ProductTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string PaymentType
        {
            get
            {
                return this.PaymentTypeField;
            }
            set
            {
                this.PaymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Services
        {
            get
            {
                return this.ServicesField;
            }
            set
            {
                this.ServicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public SpirithubCofe.Web.AramexRate.Weight ActualWeight
        {
            get
            {
                return this.ActualWeightField;
            }
            set
            {
                this.ActualWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public SpirithubCofe.Web.AramexRate.Money CashOnDeliveryAmount
        {
            get
            {
                return this.CashOnDeliveryAmountField;
            }
            set
            {
                this.CashOnDeliveryAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public SpirithubCofe.Web.AramexRate.Money InsuranceAmount
        {
            get
            {
                return this.InsuranceAmountField;
            }
            set
            {
                this.InsuranceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public SpirithubCofe.Web.AramexRate.Money CustomsValueAmount
        {
            get
            {
                return this.CustomsValueAmountField;
            }
            set
            {
                this.CustomsValueAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public SpirithubCofe.Web.AramexRate.Money CollectAmount
        {
            get
            {
                return this.CollectAmountField;
            }
            set
            {
                this.CollectAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTypeRateResult", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class ProductTypeRateResult : object
    {
        
        private string ProductGroupField;
        
        private string ProductTypeField;
        
        private string AccountEntityField;
        
        private string AccountNumberField;
        
        private double AmountField;
        
        private string CurrencyField;
        
        private double AmountBeforeTaxField;
        
        private double TaxAmountField;
        
        private double TaxRateField;
        
        private SpirithubCofe.Web.AramexRate.AdditionalCharge[] AdditionalChargesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductGroup
        {
            get
            {
                return this.ProductGroupField;
            }
            set
            {
                this.ProductGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductType
        {
            get
            {
                return this.ProductTypeField;
            }
            set
            {
                this.ProductTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string AccountEntity
        {
            get
            {
                return this.AccountEntityField;
            }
            set
            {
                this.AccountEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double AmountBeforeTax
        {
            get
            {
                return this.AmountBeforeTaxField;
            }
            set
            {
                this.AmountBeforeTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double TaxRate
        {
            get
            {
                return this.TaxRateField;
            }
            set
            {
                this.TaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public SpirithubCofe.Web.AramexRate.AdditionalCharge[] AdditionalCharges
        {
            get
            {
                return this.AdditionalChargesField;
            }
            set
            {
                this.AdditionalChargesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalCharge", Namespace="http://ws.aramex.net/ShippingAPI/v1/")]
    public partial class AdditionalCharge : object
    {
        
        private double AmountField;
        
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", ConfigurationName="SpirithubCofe.Web.AramexRate.Service_1_0")]
    public interface Service_1_0
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRate", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateRateResponse")]
        System.Threading.Tasks.Task<SpirithubCofe.Web.AramexRate.RateCalculatorResponse> CalculateRateAsync(SpirithubCofe.Web.AramexRate.RateCalculatorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateMultiRate", ReplyAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CalculateMultiRateResponse")]
        System.Threading.Tasks.Task<SpirithubCofe.Web.AramexRate.MultiRateCalculatorResponse> CalculateMultiRateAsync(SpirithubCofe.Web.AramexRate.MultiRateCalculatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RateCalculatorRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class RateCalculatorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public SpirithubCofe.Web.AramexRate.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public SpirithubCofe.Web.AramexRate.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public SpirithubCofe.Web.AramexRate.Address OriginAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public SpirithubCofe.Web.AramexRate.Address DestinationAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public SpirithubCofe.Web.AramexRate.ShipmentDetails ShipmentDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=5)]
        public string PreferredCurrencyCode;
        
        public RateCalculatorRequest()
        {
        }
        
        public RateCalculatorRequest(SpirithubCofe.Web.AramexRate.ClientInfo ClientInfo, SpirithubCofe.Web.AramexRate.Transaction Transaction, SpirithubCofe.Web.AramexRate.Address OriginAddress, SpirithubCofe.Web.AramexRate.Address DestinationAddress, SpirithubCofe.Web.AramexRate.ShipmentDetails ShipmentDetails, string PreferredCurrencyCode)
        {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.OriginAddress = OriginAddress;
            this.DestinationAddress = DestinationAddress;
            this.ShipmentDetails = ShipmentDetails;
            this.PreferredCurrencyCode = PreferredCurrencyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RateCalculatorResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class RateCalculatorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public SpirithubCofe.Web.AramexRate.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public SpirithubCofe.Web.AramexRate.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public SpirithubCofe.Web.AramexRate.Money TotalAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public SpirithubCofe.Web.AramexRate.RateDetails RateDetails;
        
        public RateCalculatorResponse()
        {
        }
        
        public RateCalculatorResponse(SpirithubCofe.Web.AramexRate.Transaction Transaction, SpirithubCofe.Web.AramexRate.Notification[] Notifications, bool HasErrors, SpirithubCofe.Web.AramexRate.Money TotalAmount, SpirithubCofe.Web.AramexRate.RateDetails RateDetails)
        {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.TotalAmount = TotalAmount;
            this.RateDetails = RateDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MultiRateCalculatorRequest", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class MultiRateCalculatorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public SpirithubCofe.Web.AramexRate.ClientInfo ClientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public SpirithubCofe.Web.AramexRate.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public SpirithubCofe.Web.AramexRate.Address OriginAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public SpirithubCofe.Web.AramexRate.Address DestinationAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=4)]
        public SpirithubCofe.Web.AramexRate.MultiRateDetails MultiRateDetails;
        
        public MultiRateCalculatorRequest()
        {
        }
        
        public MultiRateCalculatorRequest(SpirithubCofe.Web.AramexRate.ClientInfo ClientInfo, SpirithubCofe.Web.AramexRate.Transaction Transaction, SpirithubCofe.Web.AramexRate.Address OriginAddress, SpirithubCofe.Web.AramexRate.Address DestinationAddress, SpirithubCofe.Web.AramexRate.MultiRateDetails MultiRateDetails)
        {
            this.ClientInfo = ClientInfo;
            this.Transaction = Transaction;
            this.OriginAddress = OriginAddress;
            this.DestinationAddress = DestinationAddress;
            this.MultiRateDetails = MultiRateDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MultiRateCalculatorResponse", WrapperNamespace="http://ws.aramex.net/ShippingAPI/v1/", IsWrapped=true)]
    public partial class MultiRateCalculatorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=0)]
        public SpirithubCofe.Web.AramexRate.Transaction Transaction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=1)]
        public SpirithubCofe.Web.AramexRate.Notification[] Notifications;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=2)]
        public bool HasErrors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.aramex.net/ShippingAPI/v1/", Order=3)]
        public SpirithubCofe.Web.AramexRate.ProductTypeRateResult[] RateResults;
        
        public MultiRateCalculatorResponse()
        {
        }
        
        public MultiRateCalculatorResponse(SpirithubCofe.Web.AramexRate.Transaction Transaction, SpirithubCofe.Web.AramexRate.Notification[] Notifications, bool HasErrors, SpirithubCofe.Web.AramexRate.ProductTypeRateResult[] RateResults)
        {
            this.Transaction = Transaction;
            this.Notifications = Notifications;
            this.HasErrors = HasErrors;
            this.RateResults = RateResults;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface Service_1_0Channel : SpirithubCofe.Web.AramexRate.Service_1_0, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service_1_0Client : System.ServiceModel.ClientBase<SpirithubCofe.Web.AramexRate.Service_1_0>, SpirithubCofe.Web.AramexRate.Service_1_0
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service_1_0Client(EndpointConfiguration endpointConfiguration) : 
                base(Service_1_0Client.GetBindingForEndpoint(endpointConfiguration), Service_1_0Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service_1_0Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service_1_0Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service_1_0Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service_1_0Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SpirithubCofe.Web.AramexRate.RateCalculatorResponse> CalculateRateAsync(SpirithubCofe.Web.AramexRate.RateCalculatorRequest request)
        {
            return base.Channel.CalculateRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpirithubCofe.Web.AramexRate.MultiRateCalculatorResponse> CalculateMultiRateAsync(SpirithubCofe.Web.AramexRate.MultiRateCalculatorRequest request)
        {
            return base.Channel.CalculateMultiRateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Service_1_0))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Service_1_01))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Service_1_0))
            {
                return new System.ServiceModel.EndpointAddress("http://ws.aramex.net/ShippingAPI.V2/RateCalculator/Service_1_0.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Service_1_01))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.aramex.net/ShippingAPI.V2/RateCalculator/Service_1_0.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Service_1_0,
            
            BasicHttpBinding_Service_1_01,
        }
    }
}
